# Generated by Django 5.1.1 on 2024-09-17 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STHENOS_Map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteDepFr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_insee', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('nuts3', models.CharField(max_length=80)),
                ('wikipedia', models.CharField(max_length=80)),
                ('wikidata', models.CharField(max_length=80)),
                ('surf_ha', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
