# Generated by Django 5.1.1 on 2024-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STHENOS_Map', '0002_limitedepfr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedepfr',
            name='nuts3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
