"""
Django settings for STHENOS project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zs5d-t&r93(nt2gr!nv2@!$u1-w_1_zy#_d&jo=agslpe1tc2+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['16.171.149.200', 'localhost', '127.0.0.1']

USE_TZ = True  # Ensure timezone support is enabled
TIME_ZONE = 'UTC'  # Default timezone for your server

# Application definition

INSTALLED_APPS = [
    'STHENOS_Index',
    'STHENOS_Game',
    'STHENOS_Calculators',
    'STHENOS_Network',
    'STHENOS_Programs',
    'STHENOS_Theory',
    'STHENOS_Map',
    'leaflet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')

ROOT_URLCONF = 'STHENOS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'STHENOS' / 'commonTemplates', os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'STHENOS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'STHENOS',
        'USER': 'postgres',
        'PASSWORD': 'Pantheon.postgres.2018',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'STHENOS_Index.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# For development, you might not need this if your static files are in the app's static directory
STATICFILES_DIRS = [
 
     BASE_DIR / 'STHENOS' / 'static',
]

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (46.603354, 1.888334),  # Coordinates for the center of France
    'DEFAULT_ZOOM': 5,
    
    # Configuration options for Leaflet Draw plugin
    'DRAW': {
        'polyline': True,   # Enable drawing polylines
        'polygon': True,    # Enable drawing polygons
        'rectangle': True,  # Enable drawing rectangles
        'circle': True,     # Enable drawing circles
        'marker': True      # Enable adding markers
    },
    
    # Minimum zoom level of the map
    'MIN_ZOOM': 1,
    
    # Maximum zoom level of the map
    'MAX_ZOOM': 20,
    
    # Enable or disable zooming with the mouse scroll wheel
    'SCROLLWHEEL': True,
    
    # Enable or disable using Canvas rendering for performance
    'PREFER_CANVAS': False,
    
    # Custom attribution text or HTML to display on the map
    'ATTRIBUTION_PREFIX': 'Raphael Masset',
    
    # Configure whether to disable Cross-Origin Resource Sharing (CORS) on tile requests
    'NO_CORS': False,
    'SCALE': 'both'
}
